version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - cd Doc && doxygen Doxyfile

sphinx:
  configuration: Doc/conf.py

python:
  install:
    - requirements: Doc/requirements_docs.txt
