name: Lint Commit Messages
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  iwyu: # use slicer-core-sdk to do an include what you use pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: |
          sudo apt-get update && sudo apt-get install mesa-utils libx11-dev iwyu
          python3 -m venv venv
          source ./venv/bin/activate
          export SKBUILD_CMAKE_DEFINE="CMAKE_CXX_INCLUDE_WHAT_YOU_USE=/usr/bin/iwyu"
          pip wheel ./LayerDM --verbose --extra-index-url=https://vtk.org/files/wheel-sdks
